spring:
  sleuth:
    sampler:
      probability: 0
    scheduled:
      enabled: false
    enabled: true

loc:
  tomcat:
    shutdown:
      wait-time: 30
  wechat:
    miniapp:
      app-id: wxa454bc2ddc9e1bdf
      secret: 732e9c1990c03a9719d40fad6307ccc8



